### ISSUE TITLE
执行命令或者脚本时，报空指针异常

### ISSUE THREAD

**Issue by lishijiang** [i4de/go-ops#45]
报错如下：
2022/07/14 09:48:39 worker with func exits from a panic: runtime error: invalid memory address or nil pointer dereference
2022/07/14 09:48:39 worker with func exits from panic: goroutine 135134 [running]:
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1.1()

解决方法：
在pkg/system/exec_cmd_runner.go文件中在用户检测代码段做新增如下逻辑
                var attr *syscall.SysProcAttr
		if execCmd.SysProcAttr == nil {
			attr = new(syscall.SysProcAttr)
		} else {
			attr = execCmd.SysProcAttr
		}

**Comment by luxingwen** [comment]
https://github.com/i4de/go-ops/pull/46   已经合并，关闭此issue
